<?php

/**
 * Implements hook_form_FORM_ID_alter().
 * @param unknown $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param unknown $form_id
 */
function site_api_key_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    
    $form['site_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t("Site API Key"),
        '#default_value' => !empty(\Drupal::config('system.site')->get('siteapikey')) ? \Drupal::config('system.site')->get('siteapikey') : 'No API Key yet',
        '#size' => 60, 
    );
    
    $form['actions']['submit']['#submit'][]  = 'site_api_key_form_submit';
    
    if( !empty(\Drupal::config('system.site')->get('siteapikey'))  ) {
        $form['actions']['submit']['#value'] = t('Update Configuration');
    }
}

function site_api_key_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
    
    $config = \Drupal::service('config.factory')->getEditable('system.site');
    $config->set('siteapikey', $form_state->getValue('site_api_key'))
    ->save();
    
    \Drupal::messenger()->addMessage(t('Site API Key has been updated with value - ' . $form_state->getValue('site_api_key')), 'status');
    
    
}